### ISSUE TITLE
Gintronic Font

### ISSUE THREAD

**Issue by tokencoder** [cancng/fonts#1]
Gintronic:
https://wormhole.app/yLzox#2rChGUo1-wJ5l4UxI_GSNQ

Good for 24hrs.

**Comment by ToxicSmurf** [comment]
Any chance you could do another run @tokencoder ?

**Comment by tokencoder** [comment]
https://upload.disroot.org/r/EobpNKzp#RFWI9x/clZZw5RNsc8dBK5awErOndbG0R9Kyc+PhoYE=

30 day link.

**Comment by ToxicSmurf** [comment]
Thank you kindly

**Comment by uday-samsani** [comment]
Do you think Mono Lisa and Dank Mono other latest versions have new changes in font?

**Comment by tokencoder** [comment]
Dank Mono author states, "Only major issues are expected to be fixed in the font if found." and is still listed as v 1.0000 on [Gumroad](https://philpl.gumroad.com/l/dank-mono) 

[Mono Lisa Releases page](https://www.monolisa.dev/releases) has a few tweaks.

**Comment by fengtomy** [comment]
sorry to bother, but do i have a chance to try Gintronic font? it looks fancy, and it's price is nice, too

**Comment by doctor** [comment]
> https://upload.disroot.org/r/EobpNKzp#RFWI9x/clZZw5RNsc8dBK5awErOndbG0R9Kyc+PhoYE=
> 
> 30 day link.

do you have another link?

**Comment by fengtomy** [comment]
hello
thank you, but the link you post to me is invalid, and I don't have newer
versions. Whatever thanks for your help.

**Comment by doctor** [comment]
sorry about the confusion. I reposted your link and replied on top of it to check with you if you have still have the gintronic fonts to try.

**Comment by Mark2Mark** [comment]
As the designer and official publisher of Gintronic, I am subscribing myself here to to see what is happening here with these unauthorized sharings.
