### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by okonet** [cancng/fonts#5]
This repo is violating [MonoLisa license terms](https://www.monolisa.dev/license). We would like to kindly ask you to delete the repo (or remove any copyrighted content completely also scraping git history) before we start taking any legal action.

Thanks in advance.

UPDATE: Considering the old version of the font hosted and the fact there is only Regular and Bold styles there, I would propose linking to the official repo instead of removal as a win-win strategy. WDYT?

**Comment by cancng** [comment]
@okonet We can link 👍

**Comment by okonet** [comment]
That's great to hear. You can also use the free trial version if you want to keep the distribution: https://www.monolisa.dev/buy/661578
